version: 2

jobs:
  jest:
    docker:
      - image: circleci/node:lts-jessie
    steps:
      - checkout
      - restore_cache:
          keys:
            - jest-{{ checksum "package.json" }}
      - run: npm i --verbose
      - run: sudo npm i -g codecov
      - save_cache:
          key: jest-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: execute 'jest' tests with coverage
          command: npm test -- --coverage
      - run:
          name: upload coverage to codecov.io
          command: codecov
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  full-coverage:
    jobs:
      - jest
